#  Keys for elements that not raises events. If elements raises event - set event as key

from enum import Enum


class Element(str, Enum):
    pass


class Misc(Element):
    OPERATION_STATUS_FIELD = "-OPERATION-STATUS-FIELD"


class EmployeeForm(Element):
    NAME = "-EMPLOYEE-NAME-"
    SURNAME = "-EMPLOYEE-SURNAME-"
    PATRONYMIC = "-EMPLOYEE-PATRONYMIC-"

    DEPARTMENT_NUMBER = "-EMPLOYEE-DEPARTMENT-NUMBER-"
    SERVICE_NUMBER = "-EMPLOYEE-SERVICE-NUMBER-"
    EMPLOYMENT_DATE = "-EMPLOYEE-EMPLOYMENT-DATE-"
    TITLES = "-EMPLOYEE-TITLES-"

    TOPIC_NUMBER = "-EMPLOYEE-TOPIC-NUMBER"
    TOPIC_NAME = "-EMPLOYEE-TOPIC-NAME-"

    POST_CODE = "-EMPLOYEE-POST-CODE-"
    POST_NAME = "-EMPLOYEE-POST-NAME-"

    SALARY_AMOUNT = "-EMPLOYEE-SALARY-AMOUNT-"
    SALARY_CURRENCY = "-EMPLOYEE-SALARY-CURRENCY-"
