#  Keys for elements that not raises events. If elements raises event - set event as key

from enum import Enum

from .keys import Key


class Element(Key, Enum):
    pass


class Misc(Element):
    OPERATION_STATUS_FIELD = "-OPERATION-STATUS-FIELD"
    MESSAGE_FIELD = "-MESSAGE-FIELD-"


class EmployeeForm(Element):
    NAME = "-EMPLOYEE-NAME-"
    SURNAME = "-EMPLOYEE-SURNAME-"
    PATRONYMIC = "-EMPLOYEE-PATRONYMIC-"

    DEPARTMENT_NUMBER = "-EMPLOYEE-DEPARTMENT-NUMBER-"
    SERVICE_NUMBER = "-EMPLOYEE-SERVICE-NUMBER-"
    EMPLOYMENT_DATE = "-EMPLOYEE-EMPLOYMENT-DATE-"
    TITLES = "-EMPLOYEE-TITLES-NAME-"

    TOPIC_NUMBER = "-EMPLOYEE-TOPIC-NUMBER-"
    TOPIC_NAME = "-EMPLOYEE-TOPIC-NAME-"

    POST_CODE = "-EMPLOYEE-POST-CODE-"
    POST_NAME = "-EMPLOYEE-POST-NAME-"

    SALARY_AMOUNT = "-EMPLOYEE-SALARY-AMOUNT-"
    SALARY_CURRENCY = "-EMPLOYEE-SALARY-CURRENCY-"


class MainWindow(Element):
    EMPLOYEE_FORM = EmployeeForm


class Statistics(Element):
    MAX_WORK_DURATION_EMPLOYEES_COUNT = "-MAX-WORK-DURATION-EMPLOYEES-COUNT-"
    HIGHEST_PAID_EMPLOYEES_COUNT = "-HIGHEST-PAID-EMPLOYEES-COUNT-"
    TITLE_EMPLOYEES_GROWTH_HISTORY_TITLE_NAME = "-TITLE-EMPLOYEES-GROWTH-HISTORY-TITLE-NAME-"


class Forecasts(Element):
    TITLE_EMPLOYEES_GROWTH_FORECAST_TITLE_NAME = "-TITLE-EMPLOYEES-GROWTH-FORECAST-TITLE-NAME-"
    TITLE_EMPLOYEES_GROWTH_FORECAST_YEARS_COUNT = "-TITLE-EMPLOYEES-GROWTH-FORECAST-YEARS-COUNT-"


class Diagrams(Element):
    DIAGRAM_CANVAS = "-DIAGRAM-CANVAS-"
