#  Keys for elements that not raises events. If elements raises event - set event as key

from enum import Enum


class Element(str, Enum):
    pass


class Misc(Element):
    OPERATION_STATUS_FIELD = "-OPERATION-STATUS-FIELD"


class EmployeeForm(Element):
    NAME = "-EMPLOYEE-NAME-"
    SURNAME = "-EMPLOYEE-SURNAME-"
    PATRONYMIC = "-EMPLOYEE-PATRONYMIC-"

    DEPARTMENT_NUMBER = "-EMPLOYEE-DEPARTMENT-NUMBER-"
    SERVICE_NUMBER = "-EMPLOYEE-SERVICE-NUMBER-"
    EMPLOYMENT_DATE = "-EMPLOYEE-EMPLOYMENT-DATE-"
    TITLES = "-EMPLOYEE-TITLES-NAME-"

    TOPIC_NUMBER = "-EMPLOYEE-TOPIC-NUMBER-"
    TOPIC_NAME = "-EMPLOYEE-TOPIC-NAME-"

    POST_CODE = "-EMPLOYEE-POST-CODE-"
    POST_NAME = "-EMPLOYEE-POST-NAME-"

    SALARY_AMOUNT = "-EMPLOYEE-SALARY-AMOUNT-"
    SALARY_CURRENCY = "-EMPLOYEE-SALARY-CURRENCY-NAME-"


class Statistics(Element):
    MAX_WORK_DURATION_EMPLOYEES_COUNT = "-MAX-WORK-DURATION-EMPLOYEES-COUNT-"
    MAX_WORK_DURATION_EMPLOYEES_CANVAS = "-MAX-WORK-DURATION-EMPLOYEES-CANVAS-"

    HIGHEST_PAID_EMPLOYEES_COUNT = "-HIGHEST-PAID-EMPLOYEES-COUNT-"
    HIGHEST_PAID_EMPLOYEES_CANVAS = "-HIGHEST-PAID-EMPLOYEES-CANVAS-"

    TITLE_EMPLOYEES_GROWTH_HISTORY_TITLE_NAME = "-TITLE-EMPLOYEES-GROWTH-HISTORY-TITLE-NAME-"
    TITLE_EMPLOYEES_GROWTH_HISTORY_CANVAS = "-TITLE-EMPLOYEES-GROWTH-HISTORY-CANVAS-"

    EMPLOYEES_DISTRIBUTION_BY_TITLES_CANVAS = "-EMPLOYEES-DISTRIBUTION-BY-TITLES-CANVAS-"
    EMPLOYEES_DISTRIBUTION_BY_TOPICS_CANVAS = "-EMPLOYEES-DISTRIBUTION-BY-TOPICS-CANVAS-"


class Forecasts(Element):
    TITLE_EMPLOYEES_GROWTH_FORECAST_TITLE_NAME = "-TITLE-EMPLOYEES-GROWTH-FORECAST-TITLE-NAME-"
    TITLE_EMPLOYEES_GROWTH_FORECAST_YEARS_COUNT = "-TITLE-EMPLOYEES-GROWTH-FORECAST-YEARS-COUNT-"
    TITLE_EMPLOYEES_GROWTH_FORECAST_CANVAS = "-TITLE-EMPLOYEES-GROWTH-FORECAST-CANVAS-"
