# Events. Set them as keys for elements that raises events or raise directly

from enum import Enum
from typing import Callable, TypeVar

import PySimpleGUI as sg


class Event(str, Enum):
    pass


class Misc(Event):
    NON_EXISTENT = "-NON-EXISTENT-"


class EmployeeEvent(Event):
    EMPLOYEE_SELECTED = "-EMPLOYEE-SELECTED-"

    GET_EMPLOYEES = "-GET-EMPLOYEES-"
    GET_EMPLOYEES_SUCCESS = "-GET-EMPLOYEES-SUCCESS-"
    GET_EMPLOYEES_PROCESSING = "-GET-EMPLOYEES-PROCESSING"
    GET_EMPLOYEES_FAIL = "-GET-EMPLOYEES-FAIL-"

    ADD_EMPLOYEE = "-ADD-EMPLOYEE-"
    ADD_EMPLOYEE_SUCCESS = "-ADD-EMPLOYEE-SUCCESS-"
    ADD_EMPLOYEE_PROCESSING = "-ADD-EMPLOYEE-PROCESSING"
    ADD_EMPLOYEE_FAIL = "-ADD-EMPLOYEE-FAIL-"

    UPDATE_EMPLOYEE = "-UPDATE-EMPLOYEE-"
    UPDATE_EMPLOYEE_SUCCESS = "-UPDATE-EMPLOYEE-SUCCESS-"
    UPDATE_EMPLOYEE_PROCESSING = "-UPDATE-EMPLOYEE-PROCESSING-"
    UPDATE_EMPLOYEE_FAIL = "-UPDATE-EMPLOYEE-FAIL-"

    DELETE_EMPLOYEES = "-DELETE-EMPLOYEES-"
    DELETE_EMPLOYEES_SUCCESS = "-DELETE-EMPLOYEES-SUCCESS-"
    DELETE_EMPLOYEES_PROCESSING = "-DELETE-EMPLOYEES-PROCESSING-"
    DELETE_EMPLOYEES_FAIL = "-DELETE-EMPLOYEES-FAIL-"
    
    SEARCH_EMPLOYEES = "-SEARCH-EMPLOYEES-"


class StatisticsEvent(Event):
    SHOW_MAX_WORK_DURATION_EMPLOYEES = "-SHOW-MAX-WORK-DURATION-EMPLOYEES-"
    SHOW_MAX_WORK_DURATION_EMPLOYEES_SUCCESS = "-SHOW-MAX-WORK-DURATION-SUCCESS-EMPLOYEES-"
    SHOW_MAX_WORK_DURATION_EMPLOYEES_PROCESSING = "-SHOW-MAX-WORK-DURATION-PROCESSING-EMPLOYEES-"
    SHOW_MAX_WORK_DURATION_EMPLOYEES_FAIL = "-SHOW-MAX-WORK-DURATION-FAIL-EMPLOYEES-"

    SHOW_HIGHEST_PAID_EMPLOYEES = "-SHOW-HIGHEST-PAID-EMPLOYEES-EMPLOYEES-"
    SHOW_HIGHEST_PAID_EMPLOYEES_SUCCESS = "-SHOW-HIGHEST-PAID-EMPLOYEES-SUCCESS-EMPLOYEES-"
    SHOW_HIGHEST_PAID_EMPLOYEES_PROCESSING = "-SHOW-HIGHEST-PAID-EMPLOYEES-PROCESSING-EMPLOYEES-"
    SHOW_HIGHEST_PAID_EMPLOYEES_FAIL = "-SHOW-HIGHEST-PAID-EMPLOYEES-FAIL-EMPLOYEES-"

    SHOW_TITLE_EMPLOYEES_GROWTH_HISTORY = "-SHOW-TITLE-EMPLOYEES-GROWTH-HISTORY-"
    SHOW_TITLE_EMPLOYEES_GROWTH_HISTORY_SUCCESS = "-SHOW-TITLE-EMPLOYEES-GROWTH-HISTORY-SUCCESS-"
    SHOW_TITLE_EMPLOYEES_GROWTH_HISTORY_PROCESSING = "-SHOW-TITLE-EMPLOYEES-GROWTH-HISTORY-PROCESSING-"
    SHOW_TITLE_EMPLOYEES_GROWTH_HISTORY_FAIL = "-SHOW-TITLE-EMPLOYEES-GROWTH-HISTORY-FAIL-"

    SHOW_EMPLOYEES_DISTRIBUTION_BY_TITLES = "-SHOW-EMPLOYEES-DISTRIBUTION-BY-TITLES-"
    SHOW_EMPLOYEES_DISTRIBUTION_BY_TITLES_SUCCESS = "-SHOW-EMPLOYEES-DISTRIBUTION-BY-TITLES-SUCCESS-"
    SHOW_EMPLOYEES_DISTRIBUTION_BY_TITLES_PROCESSING = "-SHOW-EMPLOYEES-DISTRIBUTION-BY-TITLES-PROCESSING-"
    SHOW_EMPLOYEES_DISTRIBUTION_BY_TITLES_FAIL = "-SHOW-EMPLOYEES-DISTRIBUTION-BY-TITLES-FAIL-"

    SHOW_EMPLOYEES_DISTRIBUTION_BY_TOPICS = "-SHOW-EMPLOYEES-DISTRIBUTION-BY-TOPICS-"
    SHOW_EMPLOYEES_DISTRIBUTION_BY_TOPICS_SUCCESS = "-SHOW-EMPLOYEES-DISTRIBUTION-BY-TOPICS-SUCCESS-"
    SHOW_EMPLOYEES_DISTRIBUTION_BY_TOPICS_PROCESSING = "-SHOW-EMPLOYEES-DISTRIBUTION-BY-TOPICS-PROCESSING-"
    SHOW_EMPLOYEES_DISTRIBUTION_BY_TOPICS_FAIL = "-SHOW-EMPLOYEES-DISTRIBUTION-BY-TOPICS-FAIL-"


class ForecastsEvent(Event):
    SHOW_TITLE_EMPLOYEES_GROWTH_FORECAST = "-SHOW-TITLE-EMPLOYEES-GROWTH-FORECAST-"
    SHOW_TITLE_EMPLOYEES_GROWTH_FORECAST_SUCCESS = "-SHOW-TITLE-EMPLOYEES-GROWTH-FORECAST-SUCCESS-"
    SHOW_TITLE_EMPLOYEES_GROWTH_FORECAST_PROCESSING = "-SHOW-TITLE-EMPLOYEES-GROWTH-FORECAST-PROCESSING-"
    SHOW_TITLE_EMPLOYEES_GROWTH_FORECAST_FAIL = "-SHOW-TITLE-EMPLOYEES-GROWTH-FORECAST-FAIL-"


class WindowEvent(Event):
    OPEN = "-OPEN-WINDOW-"
    CLOSE = "-CLOSE-WINDOW-"
    OPEN_STATISTICS_WINDOW = "-OPEN-STATISTICS-WINDOW-"
    OPEN_FORECASTS_WINDOW = "-OPEN-FORECASTS-WINDOW-"


AT = TypeVar("AT")
RT = TypeVar("RT")


# On success return function result in values with success event as key, like sg.Window.perform_long_operation
def raise_status_events(
        window: sg.Window,
        success_event: Event,
        processing_event: Event,
        fail_event: Event,
) -> Callable[
    [Callable[..., RT]],
    Callable[..., RT]
]:

    def decorator(func: Callable[..., RT]) -> Callable[..., RT]:
        def wrapper(*args: AT, **kwargs: AT) -> RT:
            window.write_event_value(processing_event, None)

            try:
                result = func(*args, **kwargs)
                window.write_event_value(success_event, result)
                return result

            except Exception as err:
                window.write_event_value(fail_event, None)
                raise

        return wrapper
    return decorator
