version: "3.8"

services:
  backend:
    extends:
      file: docker-compose.dev.yml
      service: backend
    entrypoint: bash -c "
        alembic upgrade head && \
        alembic revision --autogenerate && \
        alembic upgrade head && \
        uvicorn main:app --host 0.0.0.0 --port 8000
      "

  postgres:
    extends:
      file: docker-compose.dev.yml
      service: postgres
