version: "3.8"

services:
  backend:
    build: .
    expose:
      - "8000:8000"
    environment:
      - BACKEND__DATABASE__POSTGRES_DSN=postgresql://postgres:postgres@postgres:5432/postgres
      - BACKEND__CURRENCY_EXCHANGE_RATES__API_URL=http://api.exchangeratesapi.io/v1/
      - BACKEND__CURRENCY_EXCHANGE_RATES__API_KEY
    depends_on:
      postgres:
        condition: service_healthy

  backend-reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    expose:
      - 5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 30

